sudo: required
services:
  - docker

branches:
  only:
    - master

before_install:

script:

after_success:

deploy:
  provider:
  region:
  app:
  env:
  bucket_name:
  bucket_path:
  on:
    branch:
  access_key_id:
  secret_access_key:
    secure:
